import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useSession } from "next-auth/react";
import Link from "next/link";
import { Avatar, AvatarBadge, AvatarGroup } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { data: session } = useSession();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <Avatar
            size="2xl"
            name={session?.user.userName}
            src="https://i.pravatar.cc/300"
          />{" "}
        </div>
        <div>
          <p>
            User Id:&nbsp;
            <code className={styles.code}>{session?.user.userId}</code>
          </p>
          <p>
            User Name:&nbsp;
            <code className={styles.code}>{session?.user.userName}</code>
          </p>
          <p>
            Token:&nbsp;
            <code className={styles.code}>{session?.user.accessToken}</code>
          </p>
        </div>
        <div>
          <Link href={"/logout"}>Log Out</Link>
        </div>
      </main>
    </>
  );
}
